# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57c193d03ee61d7589156c0451d8f1b96bf67c5f3af2b68c63bd0a93028f43f40c3caf1cf426fc3802fc9f89bc04a3a403214c112302d93a2d36f01f741cc253

test:
  secret_key_base: 730316c0efb11f200d12ceadf6f69366efd1a3a7eb1b3c3bc08d97b925731f07024d583fc7def3fcdda163bbea2a8a365c70f5306a17e44eacad0326d7a1725b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
